<?php

use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * @file
 * Defines a field type to display a view.
 */

/**
 * Implements hook_theme().
 */
function viewfield_theme() {
  return array(
    'viewfield_formatter_default' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function viewfield_preprocess_viewfield_formatter_default(&$variables) {
  $element = $variables['element'];
  if (!empty($element['#view_arguments'])) {
    $variables['output'] = $element['#view']->buildRenderable($element['#view_display'], array($element['#view_arguments']));
  }
  else {
    $variables['output'] = $element['#view']->buildRenderable($element['#view_display']);
  }
}
